removed matomo from docker-compose.yml
Islandora-Devops/isle-site-template pull request #44
Opened 2024-06-03 18:37 UTC by joshdentremont

This should cover https://github.com/Islandora-Devops/isle-site-template/issues/41

2024-06-03 19:18 UTC, joecorall requested changes
LGTM. Just blocking this to merge until https://github.com/Islandora-Devops/islandora-starter-site/pull/153 merges to avoid matomo 404's for new isle-site-template installs before that PR merges

2024-06-03 19:50 UTC, joecorall commented
@joshdentremont - on second pass, there's a few other places matomo is mentioned should also remove in this PR: https://github.com/search?q=repo%3AIslandora-Devops%2Fisle-site-template%20matomo&type=code

2024-06-04 17:48 UTC, joshdentremont commented
@joecorall Good catch. I have removed them all except the vscode spell checker bit, which I figured was safe to leave in as a courtesy to anyone who wants to use it.

2024-06-05 11:51 UTC, nigelgbanks approved these changes

2024-06-05 16:44 UTC, joecorall approved these changes

2024-06-05 16:45 UTC, merged