remove DNS instructions for solr, activemq, and blazegraph
Islandora-Devops/isle-site-template pull request #61
Opened 2024-09-04 14:31 UTC by joshdentremont

Since these three services are not exposed via traefik they don't need to have their DNS records set

2024-09-04 19:17 UTC, joecorall requested changes
If we're removing this from the README, should we also remove the relevant config from `docker-compose.yml` for these services?

2024-09-04 19:34 UTC, joshdentremont reviewed
If it doesn't hurt anything I would be in favour of leaving them in, since it makes them easier to toggle if someone wanted to expose them. 

They have been in the docker-compose.yml all along, with the traefik-disabled label, so this doesn't really change anything. Just specifies that there is no need to update DNS records.

That said, I don't feel strongly one way or another. We could remove the extra lines from docker-compose.yml and just document how to expose it.

2024-09-04 19:44 UTC, joecorall commented
I'm in favor of removing the config and documenting how to use SSH port forwarding to access these services if/when needed and/or having traefik limit what IP ranges can access the services. Leaving these services open to the WWW in production is a security risk, and we shouldn't have the recommended solution for needing to access the UIs for these services be opening them up world wide.

2024-09-11 17:51 UTC, joshdentremont commented
We just discussed this at the tech call and everyone is in favour of this. I will push another update to make those changes.

2024-09-24 12:01 UTC, joecorall approved these changes

2024-09-24 12:01 UTC, merged